version: '3.8'

services:
  app:
    build:
      context: .
    image: laravel-app
    container_name: laravel_app
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000  # ← هذا هو السطر الجديد
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_mang
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
